#!/bin/sh

# script to pack the application contents (files, scripts, etc.) into a .zip file for uploading as a Cloud Function

# fetch the current date
CURRENT_DATE=$(date +%Y-%m-%d)

# fetch the application file basename
BASENAME=$(basename $(pwd))

# count the number of versions of the filename
VERSION_COUNT=$(($(find ./dist -type f -name "*$BASENAME-$CURRENT_DATE*.zip" | wc -l)+1))

# compose the (final) filename
FILENAME=$BASENAME-$CURRENT_DATE-v$VERSION_COUNT.zip

# fetch (and compose) the list of pre-packaged Python libraries
PREPACKAGED_LIBRARIES=$(wget -q -O- https://raw.githubusercontent.com/GoogleCloudPlatform/buildpacks/af44f02668ce11175634137df2a406655addd69c/cmd/python/functions_framework/converter/requirements.txt | sed 's/==.*//g' | sed '/^$/d' | tr '\n' '|' | sed 's/.$//')
PREPACKAGED_LIBRARIES_PATTERN="/$PREPACKAGED_LIBRARIES|pytest/d"

# compose the list of source folders
SOURCE_FOLDERS=$(find * -type d | egrep -v '.*__|.*/|^.git|^(build|dist|tests|venv)')

# remove the contents of the build/ directory
rm -rf build/*

# copy the requirements.txt file to the build/ directory
cp requirements.txt build/

# remove local and/or unit testing references
sed -i.bak -E $PREPACKAGED_LIBRARIES_PATTERN build/requirements.txt
rm build/requirements.txt.bak

# install all dependencies into the build/ directory
pip install -t build/ -r build/requirements.txt

# remove all __pycache__ directory entries from the src/ directory
find src -type d -name '*pycache*' -exec rm -rf {} \;

# remove all .pytest_cache directory entries from the tests/ directory
find tests -type d -name '*pytest*' -exec rm -rf {} \;

# copy all application contents to the build/ directory
cp -rf $SOURCE_FOLDERS main.py build/

# enter the build/ directory
cd build

# zip the application contents
zip -r -9 ../dist/$FILENAME .

# return to the application root directory
cd ..
