#!/bin/sh

# script to pack the application contents (files, scripts, etc.) into a .zip file for uploading as a Cloud Function

# fetch the current date
CURRENT_DATE=$(date +%Y-%m-%d)

# fetch the application file basename
BASENAME=$(basename $(pwd))

# count the number of versions of the filename
VERSION_COUNT=$(($(find ./dist -type f -name "*$BASENAME-$CURRENT_DATE*.zip" | wc -l)+1))

# compose the (final) filename
FILENAME=$BASENAME-$CURRENT_DATE-v$VERSION_COUNT.zip

# compose the list of source folders
SOURCE_FOLDERS=$(find * -type d | egrep -v '.*__|.*/|^.git|^(build|dist|tests|venv)')

# remove the contents of the build/ directory
rm -rf build/*

# install all dependencies into the build/ directory
pip install -t build/ -r requirements.txt

# copy all application contents to the build/ directory
cp -rf $SOURCE_FOLDERS main.py requirements.txt build/

# enter the build/ directory
cd build

# remove local and/or unit testing references
sed -i.bak -E '/(Flask|pytest)/d' requirements.txt
rm requirements.txt.bak

# zip the application contents
zip -r ../dist/$FILENAME .

# return to the application root directory
cd ..
